server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/madhuketan13/bankapp-config-repo.git
          username: Madhuketan13
          password: ${GITHUB_TOKEN}
          clone-on-start: true
          skip-ssl-validation: true

